# Generated by Django 4.2.11 on 2024-04-25 16:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OverallDayPlot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("plot", models.ImageField(blank=True, null=True, upload_to="plot/")),
                ("date", models.DateField()),
            ],
            options={
                "verbose_name": "OverallDayPlot",
                "verbose_name_plural": "OverallDayPlots",
            },
        ),
        migrations.CreateModel(
            name="Score",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(default="User1", max_length=50)),
                ("score", models.IntegerField()),
                ("game_session", models.CharField(default="Game1", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Score",
                "verbose_name_plural": "Scores",
            },
        ),
        migrations.CreateModel(
            name="SessionPlot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("plot", models.ImageField(blank=True, null=True, upload_to="plot/")),
                ("game_session", models.CharField(default="Game1", max_length=50)),
                ("date", models.DateField()),
            ],
            options={
                "verbose_name": "SessionPlots",
                "verbose_name_plural": "SessionPlots",
            },
        ),
    ]
