# Generated by Django 5.0.1 on 2024-04-26 01:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AveragePlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plot', models.ImageField(blank=True, null=True, upload_to='plot/')),
            ],
            options={
                'verbose_name': 'AveragePlot',
                'verbose_name_plural': 'AveragePlots',
            },
        ),
    ]
