# Generated by Django 4.2.11 on 2024-04-25 07:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("scores", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="score",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
