# Generated by Django 4.2.11 on 2024-04-25 07:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("scores", "0002_alter_score_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScorePlot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("plot", models.ImageField(blank=True, null=True, upload_to="plot/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "ScorePlots",
                "verbose_name_plural": "ScoresPlots",
            },
        ),
    ]
